/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#76777d",
        "error": "#ba1a1a",
        "secondary-container": "#d5e3fd",
        "primary-container": "#131b2e",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "surface-container-low": "#f6f3f5",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-container": "#57657b",
        "on-surface-variant": "#45464d",
        "surface-tint": "#565e74",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1b1d",
        "tertiary": "#000000",
        "inverse-surface": "#303032",
        "on-surface": "#1b1b1d",
        "surface-dim": "#dcd9db",
        "background": "#fcf8fa",
        "surface-container": "#f0edef",
        "secondary-fixed-dim": "#b9c7e0",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3f0f2",
        "surface-container-high": "#eae7e9",
        "tertiary-fixed": "#fcdeb5",
        "surface": "#fcf8fa",
        "on-secondary-fixed-variant": "#3a485c",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#98805d",
        "surface-bright": "#fcf8fa",
        "secondary-fixed": "#d5e3fd",
        "secondary": "#515f74",
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#e4e2e4",
        "surface-container-highest": "#e4e2e4",
        "on-tertiary-fixed-variant": "#574425",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed": "#271901",
        "on-primary-container": "#7c839b",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0d1c2f",
        "primary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "tertiary-container": "#271901"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "base": "4px",
        "gutter": "20px",
        "lg": "24px",
        "md": "16px",
        "xs": "4px",
        "sm": "8px",
        "xl": "32px"
      },
      fontFamily: {
        "sans": ["Public Sans", "Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}

